<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.0" PrivateAssets="all" />
        <PackageReference Include="MudBlazor" Version="8.2.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\lib\" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\ChatAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\ConfiguracoesAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\IndexAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\Monitoramento.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\PoliticaAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\Pub\Actualizacao.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\Pub\Auditoria.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\Pub\Integridade.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\Pub\Manual.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\RelatorioAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\SegurancaAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\SobreAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\Info\TermoUsoAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\LoginAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\MenuAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\MenuLayoutAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\RecuperarSenhaAdmin.razor" />
      <AdditionalFiles Include="Pages\Marketer\Serviços\RegistrarAdmin.razor" />
    </ItemGroup>

</Project>
