<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.0" PrivateAssets="all" />
        <PackageReference Include="MudBlazor" Version="8.3.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\lib\" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Pages\Est\Info\Index.razor" />
      <AdditionalFiles Include="Pages\Est\Info\Login.razor" />
      <AdditionalFiles Include="Pages\Est\Info\Politica.razor" />
      <AdditionalFiles Include="Pages\Est\Info\RecuperarSenha.razor" />
      <AdditionalFiles Include="Pages\Est\Info\Seguranca.razor" />
      <AdditionalFiles Include="Pages\Est\Info\Sobre.razor" />
      <AdditionalFiles Include="Pages\Est\Info\TermoUso.razor" />
      <AdditionalFiles Include="Pages\FuncionarioAcademico\Info\Index.razor" />
      <AdditionalFiles Include="Pages\FuncionarioAcademico\Info\Login.razor" />
      <AdditionalFiles Include="Pages\FuncionarioAcademico\Info\Politica.razor" />
      <AdditionalFiles Include="Pages\FuncionarioAcademico\Info\RecuperarSenha.razor" />
      <AdditionalFiles Include="Pages\FuncionarioAcademico\Info\Seguranca.razor" />
      <AdditionalFiles Include="Pages\FuncionarioAcademico\Info\Sobre.razor" />
      <AdditionalFiles Include="Pages\FuncionarioAcademico\Info\TermoUso.razor" />
      <AdditionalFiles Include="Pages\SecretarioAcadenico\Info\Index.razor" />
      <AdditionalFiles Include="Pages\SecretarioAcadenico\Info\Login.razor" />
      <AdditionalFiles Include="Pages\SecretarioAcadenico\Info\Politica.razor" />
      <AdditionalFiles Include="Pages\SecretarioAcadenico\Info\RecuperarSenha.razor" />
      <AdditionalFiles Include="Pages\SecretarioAcadenico\Info\Seguranca.razor" />
      <AdditionalFiles Include="Pages\SecretarioAcadenico\Info\Sobre.razor" />
      <AdditionalFiles Include="Pages\SecretarioAcadenico\Info\TermoUso.razor" />
    </ItemGroup>

</Project>
